#!/usr/bin/env bash
# Render the five Homebrew formulas for a rover release.
#
# Usage: render-homebrew-formulas.sh <version> <sha256sums-file> <out-dir>
#
#   <version>          release version without the leading `v` (e.g. 0.1.0)
#   <sha256sums-file>  the SHA256SUMS file from the GitHub Release
#                      (lines of `<sha256>␠␠<filename>`)
#   <out-dir>          directory to write the `.rb` formulas into
#
# Homebrew conflict detection means only one rover formula can be installed at
# a time; every formula installs a binary named `rover`. The default `rover`
# formula ships the `basic` (no-optional-features) variant.
set -euo pipefail

version="${1:?version required}"
sums="${2:?SHA256SUMS file required}"
outdir="${3:?output directory required}"

mkdir -p "$outdir"

# Look up the sha256 for a tarball filename in the SHA256SUMS file.
sha_for() {
  local file="$1" hash
  hash="$(awk -v f="$file" '$2 == f { print $1 }' "$sums")"
  if [ -z "$hash" ]; then
    echo "::error::no sha256 for $file in $sums" >&2
    exit 1
  fi
  printf '%s' "$hash"
}

# Emit one formula.
#   $1 class name   (e.g. Rover, RoverComplete)
#   $2 formula file (e.g. rover.rb)
#   $3 variant      (e.g. basic, complete)
#   $4 extra body   (e.g. a `depends_on` line), may be empty
render() {
  local class="$1" file="$2" variant="$3" extra="$4"
  local arm_tar="rover-${version}-aarch64-apple-darwin-${variant}.tar.gz"
  local intel_tar="rover-${version}-x86_64-apple-darwin-${variant}.tar.gz"
  local arm_sha intel_sha
  arm_sha="$(sha_for "$arm_tar")"
  intel_sha="$(sha_for "$intel_tar")"

  local base="https://github.com/aaronbassett/rover/releases/download/v${version}"

  # The conflict list is every other formula name.
  local all=(rover rover-complete rover-local-inference rover-local-vision rover-headless)
  local self="${file%.rb}"
  local conflicts=()
  for f in "${all[@]}"; do
    [ "$f" = "$self" ] || conflicts+=("\"$f\"")
  done
  local conflict_list
  conflict_list="$(IFS=$'\n'; echo "${conflicts[*]}" | paste -sd ',' - | sed 's/,/, /g')"

  {
    echo "# Generated by scripts/render-homebrew-formulas.sh — do not edit by hand."
    echo "class ${class} < Formula"
    echo "  desc \"MCP server for fetching and prepping web content for LLM agents (${variant})\""
    echo "  homepage \"https://github.com/aaronbassett/rover\""
    echo "  version \"${version}\""
    echo "  license \"MIT OR Apache-2.0\""
    echo
    echo "  on_macos do"
    echo "    on_arm do"
    echo "      url \"${base}/${arm_tar}\""
    echo "      sha256 \"${arm_sha}\""
    echo "    end"
    echo "    on_intel do"
    echo "      url \"${base}/${intel_tar}\""
    echo "      sha256 \"${intel_sha}\""
    echo "    end"
    echo "  end"
    echo
    if [ -n "$extra" ]; then
      echo "  ${extra}"
      echo
    fi
    echo "  conflicts_with ${conflict_list}, because: \"each installs a \`rover\` binary\""
    echo
    echo "  def install"
    echo "    bin.install \"rover\""
    echo "  end"
    echo
    echo "  test do"
    echo "    assert_match \"rover\", shell_output(\"#{bin}/rover --help\")"
    echo "  end"
    echo "end"
  } > "$outdir/$file"
  echo "wrote $outdir/$file"
}

render Rover               rover.rb                basic           ""
render RoverComplete       rover-complete.rb       complete        "depends_on \"chromium\""
render RoverLocalInference rover-local-inference.rb local-inference ""
render RoverLocalVision    rover-local-vision.rb   local-vision    ""
render RoverHeadless       rover-headless.rb       headless        "depends_on \"chromium\""
